### ISSUE TITLE
Not working in flutter web

### ISSUE THREAD

**Issue by shaadart** [Antoinegtir/background-remover#2]
Hey, I loved to see your package, I am so happy! and so glad you made it!
the problem i am facing is that it is not removing background in Web. 

it is always in loading state. why? how  can i fix that?

**Comment by Antoinegtir** [comment]
> Hey, I loved to see your package, I am so happy! and so glad you made it!
> 
> the problem i am facing is that it is not removing background in Web. 
> 
> 
> 
> it is always in loading state. why? how  can i fix that? 

Hey, thanks for your reply, the package work only for android yet ! There is no implementation on web version currently

**Comment by shaadart** [comment]
ooh, I wished. No issues, I am trying to make it web version friendly too, by contributing towards the project.

**Comment by Antoinegtir** [comment]
> ooh, I wished. No issues, I am trying to make it web version friendly too, by contributing towards the project. 

Feel free to contribute to the repository by creating some PR if you can ;)
